### ISSUE TITLE
interoperability with rust's zigbee "common interface for the interoperability"

### ISSUE THREAD

**Issue by akrpic77** [qm3ster/zigbeer-rs#2]
just curious if implementing of https://github.com/garro95/zigbee was considered?

**Comment by qm3ster** [comment]
My personal priorities are:
1. Get some functionality going
2. Wrap as a native node js module OR copy the mqtt interface of [`zigbee2mqtt`](https://github.com/Koenkk/zigbee2mqtt).
3. With this test case, determine which an ergonomic APIs at which to split off internal crates.

I am definitely interested in a community interface that transcends dongle vendors, etc.
But first I need to get a useful application going.
I have stumbled upon [`garro95/zigbee`](https://github.com/garro95/zigbee) in the past.
At the moment, especially with the changes in the async ecosystem, it seems like too much of a moving target.

**Comment by akrpic77** [comment]
Makes sense. Thank you for answering.

**Comment by qm3ster** [comment]
Tokio 0.2 is almost upon us :weary::ok_hand:

**Comment by qm3ster** [comment]
@akrpic77 I am probably going to continue this project now, do you know anything about the status of standardization of a Zigbee interface in Rust, or what @garro95 is up to now?

**Comment by garro95** [comment]
Wow hello! The zigbee specification is very big and I did not go on very much because I was busy, but also because of low incentives. But I would be very happy to use some help!

**Comment by qm3ster** [comment]
@garro95
1. Where can I contact you in a more realtime fashion?
2. Do you have any Zigbee dongles/end devices?
